branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: josh_blog
  default_ec2_keyname: aws-eb
  default_platform: PHP 5.6
  default_region: us-west-2
  profile: eb-cli
  sc: git
